- name: add kubernetes repo
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: setenforce 0
  command: setenforce 0

- name: install packages
  yum: name="{{ item }}" state=installed
  with_items:
    - docker
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: docker service start and enabled
  service: name=docker enabled=yes state=started

- name: kubelet service start and enabled
  service: name=kubelet enabled=yes state=started