- name: create kubernetes.repo
  template:
    src: kubernetes.j2
    dest: "/etc/yum.repos.d/kubernetes.repo"

- name: setenforce 0
  command: setenforce 0

- name: install packages
  yum: name="{{ item }}" state=installed
  with_items:
    - docker
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
