# CentOS

- name: add kubernetes repo
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  when: ansible_distribution == 'CentOS'

- name: import rpm_key
  rpm_key: state=present key={{ item }}
  with_items:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  when: ansible_distribution == 'CentOS'

- name: install packages
  yum: name="{{ item }}" state=installed update_cache=yes
  with_items:
    - docker
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
  when: ansible_distribution == 'CentOS'

- name: docker service start and enabled
  service: name=docker enabled=yes state=started
  when: ansible_distribution == 'CentOS'

- name: kubelet service start and enabled
  service: name=kubelet enabled=yes state=started
  when: ansible_distribution == 'CentOS'


# Ubuntu

- name: import apt-key
  apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present
  when: ansible_distribution == 'Ubuntu'

- name: add kubernetes.list
  lineinfile:
    dest: "/etc/apt/sources.list.d/kubernetes.list"
    state: present
    create: yes
    line: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  when: ansible_distribution == 'Ubuntu'

- name: install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - docker.io
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
  when: ansible_distribution == 'Ubuntu'
